WIP radiasoft/container-sirepo-devbox#7: Move common dependencies into container-sirepo-base installer
radiasoft/container-sirepo-ci pull request #10
Opened 2023-08-07 21:18 UTC by e-carlin

Both container-sirepo-devbox and container-sirepo-ci need some common dependencies so move them into an installer and call it.

2023-08-07 21:18 UTC, e-carlin commented
Depends on https://github.com/radiasoft/download/pull/517

2023-08-07 21:30 UTC, robnagler requested changes

2023-08-07 21:30 UTC, robnagler commented on container-conf/build.sh
> +    install_repo_eval container-sirepo-base
Add run_user argument. Don't default.

2023-08-08 15:04 UTC, e-carlin commented on container-conf/build.sh
> +    install_repo_eval container-sirepo-base
756fae8

2023-08-08 16:15 UTC, robnagler approved these changes
You merge.

2023-08-08 16:37 UTC, merged